apiVersion: batch/v1
kind: Job
metadata:
  name: init-data
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            echo "Inicjalizacja danych o $(date)" > /data/init.txt
            echo "Job zakończony"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data-volume
        emptyDir: {}
