apiVersion: v1
kind: Pod
metadata:
  name: init-side
spec:
  volumes:
    - name: config-volume
      emptyDir: {}

  initContainers:
    - name: generate-config
      image: busybox
      command: ['sh', '-c']
      args:
        - echo "APP_MODE=production" > /config/config.env
      volumeMounts:
        - name: config-volume
          mountPath: /config

  containers:
    - name: sidecar
      image: busybox
      command: ['sh', '-c']
      args:
        - echo "Sidecar działa"; tail -f /config/config.env
      volumeMounts:
        - name: config-volume
          mountPath: /config
